web: {
  templates
  static: {
    styles
    scripts
  }
}

cmd: {
  main
}

internal: {
  controller
  handler
  renderer
  repository
}

cmd.main -> internal.controller

internal.controller -> internal.handler

internal.handler -> internal.repository
internal.handler -> internal.renderer

internal.renderer -> web.templates
